version: 1.0
data:
  mass_cut: 7500  # Mass cut in GeV
  path_dict: 'PATH_DICT_ATLAS_136_7500'
  cross_section_dict: 'CROSS_SECTION_ATLAS_136_7500'
  total_luminosity: 3000

cross_validation:
  enabled: true
  n_folds: 5

feature_extraction:
  n_jets: 32
  chi_mass: 1500
  suu_mass: 8000

preprocessing:
  scaler: 'minmax'  # Options: 'standard', 'minmax'
  test_size: 0.2
  random_state: 42
  oversample_signal: true

models:
  random_forest:
    n_estimators: 200
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42

  gradient_boosting:
    n_estimators: 200
    learning_rate: 0.1
    max_depth: 3
    subsample: 1.0
    colsample_bytree: 1.0
    random_state: 42

evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1_score
    - roc_auc
    - average_precision
  evaluation:
    thresholds: [0.2, 0.5, 0.8, 0.90, 0.925, 0.95, 0.96, 0.97, 0.98, 0.99]
    use_real_event_percentiles: false

visualization:
  plots:
    - roc_curve
    - pr_curve
    - feature_importances
    - sig_bkg_metrics

results:
  directory: 'results/yuu-020/m_chi-1500/136_7500'
  save_predictions: true
  save_feature_importances: true

logging:
  file_path: 'logs/experiment.log'
  level: 'INFO'
